# Workflow - OBS Build

name: TestBuild

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
        logLevel:
          description: 'Manual Build'
          required: false
          default: 'build'
          type: choice
          options:
          - build

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Setuping Environment
        run: echo Complete

      # Runs a set of commands using the runners shell
      - name: Building OBS From Latest source code
        run: |
          sudo apt install git -y
          git clone --recursive https://github.com/obsproject/obs-studio.git
          cd obs-studio
          sudo chmod +x CI/build-linux.sh
          ./CI/build-linux.sh -p -pkg
          ls -lah build
          echo "OBS SC Dir List"
          ls -lah $PWD
      
      - name: Uploading Files for Download (Step 1)
        uses: actions/upload-artifact@v3
        with:
          name: obs-studio-29.1.0-5436342331-Linux.tar.gz
          path: /home/runner/work/kbaraniak/kbaraniak/obs-studio/build/obs-studio-29.1.0-5436342331-Linux.tar.gz      
          
      - name: Uploading Files for Download (Step 2)
        uses: actions/upload-artifact@v3
        with:
          name: obs-studio-29.1.0-5436342331-Linux.tar.Z
          path: /home/runner/work/kbaraniak/kbaraniak/obs-studio/build/obs-studio-29.1.0-5436342331-Linux.tar.Z     
          
      - name: Uploading Files for Download (Step 3)
        uses: actions/upload-artifact@v3
        with:
          name: obs-studio-29.1.0-5436342331-Linux.sh
          path: /home/runner/work/kbaraniak/kbaraniak/obs-studio/build/obs-studio-29.1.0-5436342331-Linux.sh
